"""
report_generator.py
Generates a Markdown + JSON incident report from the full pipeline output.
"""
import json
import os
from datetime import datetime
from core.config import OUTPUT_DIR


def generate_markdown_report(events, detections, timeline, overall_risk, llm_result, meta=None):
    meta = meta or {}
    now = datetime.utcnow().isoformat()

    lines = []
    lines.append(f"# Incident Report\n")
    lines.append(f"**Generated:** {now} UTC  ")
    lines.append(f"**Source:** {meta.get('source_name', 'uploaded log file')}  ")
    lines.append(f"**Total events analyzed:** {len(events)}  ")
    lines.append(f"**Overall Risk Score:** {overall_risk['score']} ({overall_risk['label']})\n")

    lines.append("## Executive Summary (AI Analysis)\n")
    if llm_result.get("error"):
        lines.append(f"> LLM analysis unavailable: {llm_result['error']}\n")
    else:
        lines.append(f"_Generated by {llm_result.get('provider')} ({llm_result.get('model')})_\n")
        lines.append(llm_result.get("analysis", "") + "\n")

    lines.append("## Detections\n")
    if not detections:
        lines.append("No detections triggered.\n")
    for d in detections:
        lines.append(f"### {d['rule']}  — `{d.get('risk_label','?')}` (score {d.get('risk_score','?')})")
        lines.append(f"- **Severity:** {d.get('severity')}")
        mitre = d.get("mitre", {})
        lines.append(f"- **MITRE ATT&CK:** {mitre.get('tactic')} — {mitre.get('technique')} ({mitre.get('technique_id')})")
        if d.get("src_ip"):
            lines.append(f"- **Source IP:** {d.get('src_ip')}")
        if d.get("user"):
            lines.append(f"- **User:** {d.get('user')}")
        ti = d.get("threat_intel") or []
        if ti:
            for t in ti:
                lines.append(f"- **Threat Intel ({t.get('ip')}):** reputation={t.get('reputation')}, sources={[s.get('source') for s in t.get('sources', [])]}")
        lines.append(f"- **Description:** {d.get('description')}")
        lines.append(f"- **Related events:** {len(d.get('event_ids', []))}\n")

    lines.append("## Timeline\n")
    lines.append("| Timestamp | Rule | Severity | Src IP | User | Host | Message |")
    lines.append("|---|---|---|---|---|---|---|")
    for t in timeline[:100]:
        msg = (t.get("message") or "").replace("|", "/")[:80]
        lines.append(f"| {t.get('timestamp')} | {t.get('rule')} | {t.get('severity')} | "
                      f"{t.get('src_ip') or '-'} | {t.get('user') or '-'} | {t.get('host') or '-'} | {msg} |")

    lines.append("\n## Top Risk Items\n")
    for d in overall_risk.get("top_risks", []):
        lines.append(f"- **{d['rule']}** — score {d['risk_score']} ({d['risk_label']})")

    report_text = "\n".join(lines)
    return report_text


def save_report(report_text: str, json_payload: dict, name_prefix="incident_report"):
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    md_path = os.path.join(OUTPUT_DIR, f"{name_prefix}_{ts}.md")
    json_path = os.path.join(OUTPUT_DIR, f"{name_prefix}_{ts}.json")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(report_text)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_payload, f, indent=2, default=str)

    return md_path, json_path
